### ISSUE TITLE
"who is this for?" should we move "you are interested in teaching CodeRefinery lessons"...

### ISSUE THREAD

**Issue by dianaiusan** [coderefinery/community-teaching#1]
"Who is the course for? 
You are interested in teaching CodeRefinery lessons..."
(https://coderefinery.org/community-teaching/#who-is-the-course-for)

I wonder if we should move the paragraph _You are interested in teaching CodeRefinery lessons, and would like a comprehensive kickstart to how CodeRefinery works either to join us, or teach its lessons with us or independently._ further down so that we do not put off persons that teach in general, especially as the focus for the event is not learning how to teach CR lessons.

I would swap this paragraph with _You run a practical teaching program at your institution (for example as part of a research computing group) and would like to learn best practices for collaborative teaching, so that you aren’t re-inventing the same thing over and over again._

I can PR if we agree.

**Comment by rkdarst** [comment]
Good idea, sounds good to me!  I agree with the reasoning.

Can you make the pull request?
