### ISSUE TITLE
Make images zoomable

### ISSUE THREAD

**Issue by bast** [coderefinery/community-teaching#41]
A good workaround is to click on them but still it would be nice to get a more intuitive zoom behavior when presenting the tech setup page.

**Comment by bast** [comment]
After some experimentation I think the current setup is actually good. Keeping.

**Comment by rkdarst** [comment]
I think it is coded as "width: 45%" (in the sphinx directive, this is
easy to change).  So it sort of makes sense it doesn't get bigger when
you zoom, even though it would be useful here.

How do web pages normally work?  It seems that this theme uses
"max-width: 800px" for the main column.  So should all image sizes be
defined relative to that, so change width to, for example, 350px?
